### ISSUE TITLE
Placeholder ipv input

### ISSUE THREAD

**Issue by kosterm14** [moonlightlizaa/connecting-people-my-first-chatroom#1]
## Probleem
Het is nu mogelijk om je placeholder te editen

![image](https://github.com/moonlightlizaa/connecting-people-my-first-chatroom/assets/61830362/290a76ae-d87f-4680-8077-69940d8a1146)

![image](https://github.com/moonlightlizaa/connecting-people-my-first-chatroom/assets/61830362/362ba29a-6b52-480b-84a7-b8b9357394d5)

## Oorzaak
https://github.com/moonlightlizaa/connecting-people-my-first-chatroom/blob/a9aba51aef1abc7f22ce7ed5f3cbce6c64ccf9c9/public/index.html#L47-L53

Ik heb je code geinspect element en ik kwam er zo achter dat je een placeholder maakt door een standaard value aan te geven aan je input.

## Oplossing
In HTML is een `<placeholder>` element te vinden. Dit is precies wat je zoekt!

https://www.w3schools.com/tags/att_input_placeholder.asp

**Comment by moonlightlizaa** [comment]
Bedankt! Ik heb het nu aangepast
